[rayhead]
rayhead ansible_host=192.168.2.42

[rayworkers]
rayworker1 ansible_host=192.168.2.197
rayworker2 ansible_host=192.168.2.254

[raycluster:children]
rayhead
rayworkers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_connection=ssh
ansible_user=appuser
