version: "3.8"

services:
  spark-master:
    image: a1-spark-master:latest
    hostname: sparkmaster
    container_name: spark-master
    ports:
      - "8080:8080"   # Spark Web UI
      - "7077:7077"   # Spark master port
    command: >
      sh -c "$${SPARK_HOME}/sbin/start-master.sh && tail -f /dev/null"
    networks:
      - spark-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager # Keep the master on the manager node

  spark-worker:
    image: a1-spark-worker:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    command: >
      sh -c "$${SPARK_HOME}/sbin/start-slave.sh spark://sparkmaster:7077 && tail -f /dev/null"
    networks:
      - spark-network
    deploy:
      replicas: 2 # Let's spin up 2 workers to demonstrate Swarm scaling!
      restart_policy:
        condition: on-failure

networks:
  spark-network:
    driver: overlay
