[rayhead]
rayhead ansible_host=<VM1-INTERNAL-IP>

[rayworkers]
rayworker1 ansible_host=<VM2-INTERNAL-IP>
rayworker2 ansible_host=<VM3-INTERNAL-IP>

[raycluster:children]
rayhead
rayworkers

[all:vars]
ansible_python_interpreter=/usr/bin/python3

[rayhead:vars]
ansible_connection=ssh
ansible_user=appuser

[rayworkers:vars]
ansible_connection=ssh
ansible_user=appuser
